# Generated by Django 5.0.6 on 2024-05-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_person_quizz_end_time_person_quizz_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='quizz_end_time',
            field=models.DateTimeField(null=True, verbose_name='horário que terminou o quizz'),
        ),
    ]
